name:                hs-tendermint-client
version:             0.1.0.0
github:              "f-o-a-m/kepler/hs-tendermint-client"
license:             Apache
author:              "Martin Allen"
maintainer:          "martin@foam.spacem"
copyright:           "2020 FOAM"

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/kepler/blob/master/hs-tendermind-client/README.md>

default-extensions:
- NamedFieldPuns
- RecordWildCards
- FlexibleContexts
- DeriveGeneric
- TypeFamilies
- TypeApplications
- GADTs
- DataKinds
- PolyKinds
- RankNTypes
- DataKinds
- ScopedTypeVariables
- FlexibleInstances
- OverloadedStrings
- GeneralizedNewtypeDeriving

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- exceptions
- data-default-class


library:
  source-dirs: src
  dependencies:
    - aeson-casing
    - conduit
    - hs-abci-types
    - http-client
    - http-conduit
    - lens
    - lens-aeson
    - mtl
    - random
    - stm
    - stm-conduit
    - string-conversions
    - text
    - transformers
    - websockets
    - wuss
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  exposed-modules:
  - Network.Tendermint.Client
  - Network.Tendermint.Client.Internal.RPCClient

tests:
  hs-tendermint-client-kv:
    main:                Spec.hs
    source-dirs:         kv-test
    other-modules:
    - KVStore.Test.KVSpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - aeson-pretty
      - conduit
      - hs-abci-types
      - hs-tendermint-client
      - hspec
      - lens
      - lens-aeson
      - text
      - random
      - string-conversions
      - unordered-containers
